quotes=[
    '"Be the change that you wish to see in the world." - Mahatma Gandhi',
    '"Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has." - Margaret Mead',
    '"Change is painful, but nothing is as painful as staying stuck somewhere you don\'t belong." - Mandy Hale',
    '"Those who cannot change their minds cannot change anything." - George Bernard Shaw',
    '"Everyone thinks of changing the world, but no one thinks of changing himself." - Leo Tolstoy'
    '"Change is the law of life. And those who look only to the past or present are certain to miss the future." - John F. Kennedy',
    '"We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty."- Maya Angelou',
    '"Dreams are the seeds of change. Nothing ever grows without a seed, and nothing ever changes without a dream." - Debby Boone',
    '"Here\'s to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They\'re not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can\'t do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do." - Rob Siltanen',
     '"The world is changed by your example, not by your opinion." - Paulo Coelho',
    '"If you don\'t build your dream, someone else will hire you to help them build theirs." - Dhirubhai Ambani',
    '"I\'m not in this world to live up to your expectations and you\'re not in this world to live up to mine." - Bruce Lee',
    '"What\'s right is what\'s left if you do everything else wrong." - Robin Williams',
    '"Be a fruitloop in a world of Cheerios." - Unknown',
    '"Dream beautiful dreams, and then work to make those dreams come true." - Spencer W. Kimball',
    '"Be the change you want to see in the world." - Mahatma Gandhi',
    '"Believe you can and you will." - Unknown',
    '"Do the right thing even when no one is looking." - Unknown',
    '"Make today the day you learn something new." -Unknown',
    '"Be silly, be honest, be kind." - Ralph Waldo Emerson',
    '"If you think someone could use a friend. Be one." - Unknown',
    '"It\'s not what happens to you but how you react to it that matters." - Epictetus',
    '"You don\'t have to be perfect to be amazing." - Unknown',
    '"The best way to predict your future is to create it." - Abraham Lincoln',
    '"Successful people are not gifted; they just work hard, then succeed on purpose." - G.K. Nielson',
    '"Don\'t watch the clock; do what it does. Keep going." - Sam Levenson',
    '"Work until your rivals become idols." - Drake',
]