quotes=[
    '"Never regret a day in your life. Good days bring you happiness and bad days give you experience." - Unknown',
    '"Either you run the day, or the day runs you." - Jim Rohn',
    '"Only I can change my life. No one can do it for me." - Carol Burnett',
    '"Life is 10% what happens to you and 90%,how you react to it." - Charles R. Swindoll',
    '"Act as if what you do makes a difference. It does." - William James',
    'When the pain of an obstacle is too great, challenge yourself to be stronger.',
    '"Even if you\'re on the right track, you\'ll get run over if you just sit there." - Will Rogers',
    '"Very little is needed to make a happy life; it is all within yourself, in your way of thinking." - Marcus Aurelius ',
    '"Life is either a daring adventure or nothing at all." Helen Keller',
    '"The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has been before.\' - Albert Einstein',
    '"Life\'s like a movie, write your own ending. Keep believing, keep pretending." - Jim Hensen',
    '"The only thing standing in the way between you and your goal is the BS story you keep telling yourself as to why you can\'t achieve it." - Jordan Belfort',
    '"What is life without a little risk?" - J.K. Rowling',
    '"Only do what your heart tells you." - Princess Diana',
    '"If it\'s a good idea, go ahead and do it. It\'s much easier to apologize than it is to get permission." - Grace Hopper',
    '"I attribute my success to this: I never gave or took an excuse." - Florence Nightingale',
    '"The question isn\'t who is going to let me; it\'s who is going to stop me." - Ayn Rand',
    '"A surplus of effort could overcome a deficit of confidence." - Sonia Sotomayer',
    '"And, when you want something, all the universe conspires in helping you to achieve it." -Paulo Coelho, The Alchemist',
    '"Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won\'t feel insecure around you. We are all meant to shine, as children do." - Marianne Williamson, A Return to Love: Reflections on the Principles of "A Course in Miracles"',
    '"Don\'t think or judge, just listen."-Sarah Dessen, Just Listen',
    '"I can be changed by what happens to me. But I refuse to be reduced by it." - Maya Angelou, Letter to My Daughter',
    '"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that." -Martin Luther King Jr., A Testament of Hope: The Essential Writings and Speeches',
    'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You\'re on your own. And you know what you know. And YOU are the one who\'ll decide where to go…" -Dr. Seuss, Oh, the Places You\'ll Go!',
    '"It\'s the possibility of having a dream come true that makes life interesting." -Paulo Coelho, The Alchemist',
    '"There is some good in this world, and it\'s worth fighting for." - J.R.R. Tolkien, The Two Towers',
    '"Learn to light a candle in the darkest moments of someone\'s life. Be the light that helps others see; it is what gives life its deepest significance."-Roy T. Bennett, The Light in the Heart',
    '"Atticus, he was real nice." "Most people are, Scout, when you finally see them." -Harper Lee, To Kill a Mockingbird',
    '"Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it." - The Lion King',
    '"We\'re on the brink of adventure, children. Don\'t spoil it with questions." - Mary Poppins',
    '"Life moves pretty fast. If you don\'t stop and look around once in a while, you could miss it."- Ferris Bueller',
    '"I just wanna let them know that they didn\'t break me." - Pretty in Pink',
]
