quotes=[
    '"A reader lives a thousand lives before he dies. The man who never reads lives only one." - George R.R. Martin',
    '"I find television very educating. Every time somebody turns on the set, I go into the other room and read a book." - Groucho Marx',
    '"Never stop learning because life never stops teaching." -Unknown',
    '"If you\'re the smartest person in the room, you\'re in the wrong room." - Unknown',
    '"The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice."- Brian Herbert',
    '"The man who does not read has no advantage over the man who cannot read."- Mark Twain',
    '"To learn a language is to have one more window from which to look at the world." - Chinese Proverb',
    '"I\'m still learning." - Michelangelo',
    '"Live as if you were to die tomorrow. Learn as if you were to live forever." - Mahatma Gandhi',
    '"Education is the most powerful weapon you can use to change the world." - Nelson Mandela',
    '"This is a reminder to you to create your own rule book, and live your life the way you want it." - Reese Evans',
    '"If you don\'t get out of the box you\'ve been raised in, you won\'t understand how much bigger the world is." - Angelina Jolie',
    '"Do the best you can. No one can do more than that." - John Wooden',
    '"Do what you can, with what you have, where you are." - Theodore Roosevelt',
    '"It\'s never too late to be what you might\'ve been." - George Eliot',
    '"If you can dream it, you can do it." - Walt Disney',
    '"Trust yourself that you can do it and get it." - Baz Luhrmann',
    '"Don\'t let what you can\'t do interfere with what you can do." - Unknown',
    '"You can do anything you set your mind to." - Benjamin Franklin',
    '"All we can do is the best we can do." - David Axelrod',
    '"You never know what you can do until you try." - William Cobbett',
    '"Twenty years from now you\'ll be more disappointed by the things you did not do than the ones you did." - Mark Twain',
    '"I am thankful for all of those who said NO to me. It\'s because of them I\'m doing it myself." - Wayne W. Dyer',
    'It\'s okay to outgrow people who don\'t grow. Grow tall anyways.',
    'When you feel like giving up just remember that there are a lot of people you still have to prove wrong.',
    '"The world is full of nice people. If you can\'t find one, be one." - Nishan Panwar',
]
