quotes=[
    '"No matter what people tell you, words and ideas can change the world." - Robin Williams',
    '"Life is like riding a bicycle. To keep your balance, you must keep moving." - Albert Einstein',
    '"You\'re off to Great Places! Today is your day! Your mountain is waiting, so… get on your way!" - Dr. Seuss',
    '"When thinking about life, remember this: no amount of guilt can change the past and no amount of anxiety can change the future." - Unknown',
    '"A negative mind will never give you a positive life." - Unknown',
    '"Everything is hard before it is easy." - Goethe',
    '"At the end of the day we can endure much more than we think we can." - Frida Kahlo',
    '"Whatever you do never run back to what broke you." - Frank Ocean',
    '"Take the risk or lose the chance." - Unknown',
    '"I didn\'t learn to be quiet when I had an opinion. The reason they knew who I was is because I told them." - Ursula Burns',
    '"Success is liking yourself, liking what you do, and liking how you do it." - Maya Angelou',
    '"If you obey all the rules, you miss all the fun." - Katharine Hepburn',
    '"You were born to be a player. You were meant to be here. This moment is yours." - Herb Brooks',
    '"Life is not what you alone make it. Life is the input of everyone who touched your life and every experience that entered it. We are all part of one another." - Yuri Kochiyama',
    '"When you reach the end of your rope, tie a knot and hang out." - Abraham Lincoln',
    '"Never regret anything that made you smile." - Mark Twain',
    '"You must do the thing you think you cannot do." - Eleanor Roosevelt',
    '"If you want to fly give up everything that weighs you down." - Buddha',
    '"Doubt kills more dreams than failure ever will." - Suzy Kassem',
    '"I never lose. Either I win or learn." - Nelson Mandela',
    '"Today is your opportunity to build the tomorrow you want." - Ken Poirot',
    '"Getting over a painful experience is much like crossing the monkey bars. You have to let go at some point in order to move forward." - C.S. Lewis',
    'Focus on being productive instead of busy." - Tim Ferriss',
    '"You don\'t need to see the whole staircase, just take the first step." - Martin Luther King Jr.',
    '"It\'s not all sunshine and rainbows, but a good amount of it actually is." - Unknown',
    'When someone says you can\'t do it, do it twice and take pictures.',
    '"I didn\'t get there by wishing for it, but by working for it." - Estee Lauder',
    '"She remembered who she was and the game changed." - Lalah Deliah',
    '"If you\'re too comfortable, it\'s time to move on. Terrified of what\'s next? You\'re on the right track." - Susan Fales-Hill',
    '"Be happy with what you have while working for what you want." - Helen Keller',
    '"Sunshine all the time makes a desert." - Arabic Proverb',

]