quotes=[
    '"It\'s not your salary that makes you rich, it\'s your spending habits.” - Charles A. Jaffe',
    '"Don\'t stay in bed unless you can make money in bed.” - George Burns',
    '"You must gain control over your money or the lack of it will forever control you.” - Dave Ramsey',
    '"Only buy something that you\'d be perfectly happy to hold if the market shuts down for ten years.”- Warren Buffett',
    '"That man is richest whose pleasures are cheapest.” - Henry David Thoreau',
    '"Money can\'t buy happiness, but it can make you awfully comfortable while you\'re being miserable.” - Clare Boothe Luce',
    '"Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.” - Jen Sincero',
    '"You\'re already a financial trader. You might not think of it in just this way, but if you work for a living, you\'re trading your time for money. Frankly, it\'s just about the worst trade you can make. Why? You can always get more money, but you can\'t get more time.” - Tony Robbins',
    '"You can only become truly accomplished at something you love. Don\'t make money your goal. Instead pursue the things you love doing and then do them so well that people can\'t take their eyes off of you.”- Maya Angelou',
    '"Formal education will make you a living; self-education will make you a fortune.” -Jim Rohn',
    '"I choose to make the rest of my life, the best of my life." - Louise Hay',
    '"Nothing can dim the light that shines from within." - Maya Angelou',
    '"Be so good they can\'t ignore you." - Steve Martin',
    '"Take criticism seriously, but not personally. If there is truth or merit in the criticism, try to learn from it. Otherwise, let it roll right off you." - Hillary Clinton',
    '"Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got to keep going." - Chantal Sutherland',
    '"A walk to a nearby park may give you more energy and inspiration in life than spending two hours in front of a screen." - Tsang Lindsay',
    '"If you can\'t do anything about it then let it go. Don\'t be a prisoner to things you can\'t change." - Tony Gaskins',
    '"You can\'t go back and change the beginning, but you can start where you are and change the ending." - C.S. Lewis',
    '"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself." - Rumi',
    '"I can and I will. Watch me." - Carrie Green',
    '"Try not to become a man of success, but rather become a man of value." - Albert Einstein',
    '"A winner is a dreamer who never gives up." - Nelson Mandela',
    '"If you don\'t have a competitive advantage, don\'t compete." - Jack Welch',
    '"I\'m going to make him an offer he can\'t refuse." - The Godfather',

]
