quotes=[
    '"All our dreams can come true, if we have the courage to pursue them." - Walt Disney',
    '"The secret of getting ahead is getting started." - Mark Twain',
    '"I\'ve missed more than 9,000 shots in my career. I\'ve lost almost 300 games. 26 times I\'ve been trusted to take the game winning shot and missed. I\'ve failed over and over and over again in my life and that is why I succeed." - Michael Jordan',
    '"Don\'t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve." - Mary Kay Ash',
    '"The best time to plant a tree was 20 years ago. The second best time is now." - Chinese Proverb',
    '"Only the paranoid survive." - Andy Grove',
    '"It\'s hard to beat a person who never gives up." - Babe Ruth',
    '"I wake up every morning and think to myself, how far can I push this company in the next 24 hours." - Leah Busque',
    '"If people are doubting how far you can go, go so far that you can\'t hear them anymore." - Michele Ruiz',
    '"We need to accept that we won\'t always make the right decisions, that we\'ll screw up royally sometimes - understanding that failure is not the opposite of success, it\'s part of success." - Arianna Huffington',
    '"Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE." - Joss Whedon',
    '"You\'ve gotta dance like there\'s nobody watching, love like you\'ll never be hurt, sing like there\'s nobody listening, and live like it\'s heaven on earth." -William W. Purkey',
    '"Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten."-Neil Gaiman',
    '"Everything you can imagine is real."-Pablo Picasso',
    '"When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us." -Helen Keller',
    '"Do one thing every day that scares you."-Eleanor Roosevelt',
    '"It\'s no use going back to yesterday, because I was a different person then."-Lewis Carroll',
    '"Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers." - Socrates',
    '"Do what you feel in your heart to be right - for you\'ll be criticized anyway."-Eleanor Roosevelt',
    '"Happiness is not something ready made. It comes from your own actions." -Dalai Lama XIV',
    '"Whatever you are, be a good one." -Abraham Lincoln',
    '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." - Aristotle',
    '"If you\'re offered a seat on a rocket ship, don\'t ask what seat! Just get on." - Sheryl Sandberg',
    '"I always did something I was a little not ready to do. I think that\'s how you grow. When there\'s that moment of Wow, I\'m not really sure I can do this,\' and you push through those moments, that\'s when you have a breakthrough." - Marissa Mayer',
    '"Never allow a person to tell you no who doesn\'t have the power to say yes." - Eleanor Roosevelt',
    '"At any given moment you have the power to say: this is not how the story is going to end." - Unknown',
    '"Amateus sit around and wait for inspiration. The rest of us just get up and go to work." - Stephen King',
    '"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven\'t found it yet, keep looking. Don\'t settle. As with all matters of the heart, you\'ll know when you find it." - Steve Jobs',
    '"Nothing will work unless you do." - Maya Angelou',
    '"Sometimes when you\'re in a dark place you think you\'ve been buried but you\'ve actually been planted." - Christine Caine',
    '"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do." - Pele',
    '"Would you like me to give you a formula for success? It\'s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn\'t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that\'s where you will find success." - Thomas J. Watson',
    '"Every champion was once a contender that didn\'t give up." - Gabby Douglas',
    '"To be a champion, I think you have to see the big picture. It\'s not about winning and losing; it\'s about every day hard work and about thriving on a challenge. It\'s about embracing the pain that you\'ll experience at the end of a race and not being afraid. I think people think too hard and get afraid of a certain challenge." - Summer Sanders',
    'Don\'t dream about success. Get out there and work for it.',
    '"The difference between successful people and very successful people is that very successful people say no\' to almost everything." - Warren Buffett',
    'You can cry, scream, and bang your head in frustration but keep pushing forward. It\'s worth it.',
    '"I hated every minute of training, but I said, Don\'t quit. Suffer now and live the rest of your life as a champion." - Muhammad Ali',
    '"Opportunities don\'t happen. You create them." - Chris Grosser',
    '"The big lesson in life is never be scared of anyone or anything." - Frank Sinatra',
    '"It\'s my life It\'s now or never I ain\'t gonna live forever I just want to live while I\'m alive" - It\'s My Life, Bon Jovi',
    '"I could build a castle out of all the bricks they threw at me" - New Romantics, Taylor Swift',
    '"Cause the grass is greener under me bright as technicolor, I can tell that you can see" - Sorry Not Sorry, Demi Lovato',
    '"Every day women and men become legends" - Glory, John Legend and Common',
    '"On my own I will just create and if it works, it works. And if it doesn\'t, I\'ll just create something else. I don\'t have any limitations on what I think I could do or be." - Oprah Winfrey',
    '"We realize the importance of our voices only when we are silenced." - Malala Yousafzai',
    '"We need to accept that we won\'t always make the right decisions, that we\'ll screw up royally sometimes - understanding that failure is not the opposite of success, it\'s part of success." - Arianna Huffington',
    '"Don\'t compromise yourself. You\'re all you\'ve got." - Janis Joplin',
    '"When something I can\'t control happens, I ask myself: Where is the hidden gift? Where is the positive in this?" - Sara Blakely',
    '"Doubt is a killer. You just have to know who you are and what you stand for. " - Jennifer Lopez',
    '"Be a first rate version of yourself, not a second rate version of someone else." - Judy Garland',
    '"Learn from the mistakes of others. You can\'t live long enough to make them all yourself." - Eleanor Roosevelt',
    '"I was smart enough to go through any door that opened." - Joan Rivers',
    '"Done is better than perfect." - Sheryl Sandberg',
    '"If your dreams don\'t scare you, they are too small." - Richard Branson',
    '"Today is your opportunity to build the tomorrow you want." - Ken Poirot',
    '"What hurts you blesses you." - Rumi',
    '"Nothing is stronger than a broken man rebuilding himself." - Unknown',
    '"I always thought it was me against the world and then one day I realized it\'s just me against me." - Kendrick Lamar',
    '"A man is not finished when he is defeated. He is finished when he quits." - Richard Nixon',  
    '"You could rattle the stars," she whispered. "You could do anything, if only you dared. And deep down, you know it, too. That\'s what scares you most." -Sarah J. Maas',
    '"It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. - Walter Anderson',
    '"The adventure of life is to learn. The purpose of life is to grow. The nature of life is to change. The challenge of life is to overcome. The essence of life is to care. The opportunity of like is to serve. The secret of life is to dare. The spice of life is to befriend. The beauty of life is to give." - William Arthur Ward',
    '"When you know your worth, no one can make you feel worthless." - Unknown',
    '"If you\'ve never eaten while crying you don\'t know what life tastes like." - Johann Wolfgang von Goethe',
    '"If you judge people, you have no time to love them." - Mother Teresa',
    '"Once you do know what the question actually is, you\'ll know what the answer means."- Douglas Adams',
    '"The two most important days in your life are the day you\'re born and the day you find out why." - Mark Twain',
    '"Nothing ever goes away until it teaches us what we need to know." - Pema Chodron',
    '"We can see through others only when we can see through ourselves." - Bruce Lee',  
]
