quotes=[
    '"What is coming is better than what is gone." - Unknown',
    '"Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely."- Roy T. Bennett',
    '"Dwell on the beauty of life. Watch the stars, and see yourself running with them." - Marcus Aurelius',
    '"Do something today that your future self will thank you for." -Unknown',
    '"The greatest weapon against stress is the ability to choose one thought over another." - William James',
    '"It takes nothing to join the crowd. It takes everything to stand alone." - Hans F. Hansen',
    '"Your mind is powerful. When you fill it with positive thoughts your whole world will change." - Unknown',
    '"Your only limit is your mind." - Unknown',
    '"Stop being afraid of what can go wrong and start being positive about what can go right." - Unknown',
    '"The difference between who you are and who you want to be is what you do." - Unknown',
    '"You can\'t have a million dollar dream on a minimum wage work ethic." - Unknown',
    '"You must do the kind of things you think you cannot do." - Eleanor Roosevelt',
    '"It\'s not what you do once in a while it\'s what you do day in and day out that makes the difference." - Jenny Craig',
    '"Falling down is how we grow. Staying down is how we die." - Brian Vaszily',
    '"Wealth isn\'t about having a lot of money it\'s about having a lot of options." - Chris Rock',
    '"There may be people that have more talent than you, but there\'s no excuse for anyone to work harder than you." - Derek Jeter',
    '"It is never too late to be what you might have been." - George Eliot ',
    '"Words can inspire, thoughts can provoke, but only action truly brings you closer to your dreams." - Brad Sugars',
    '"Don\'t stop when you are tired. Stop when you are done." - Unknown',
    '"Don\'t tell people about your dreams. Show them your dreams." - Unknown',
    '"Revenge is a powerful motivator." - Marcus Luttrell',
    '"Motivation may be what starts you off, but it\'s habit that keeps you going back for more."  - Miya Yamanouchi',
    '"I will not erase all my hard work this week because it\'s the weekend." - Unknown',
    '"It might not be easy but it\'ll be worth it." - Unknown',
    '"Make your fear of losing your greatest motivator.\' - Unknown',
    '"You will never always be motivated, so you must learn to be disciplined." -Unknown',
    '"I\'m not a product of my circumstances. I am a product of my decisions." - Stephen Covey',
]
