quotes=[
    '"Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength." - Arnold Schwarzenegger',
    '"If it doesn\'t challenge you, it doesn\'t change you." - Fred DeVito',
    '"A dream doesn\'t become reality through magic; it takes sweat, determination and hard work." - Colin Powell',
    '"Every night her thoughts weighed heavily on her soul but every morning she would get up and fight another day, every night she survived." - R.H. Sin',
    '"Still, I rise." - Maya Angelou',
    '"The best thing you can do is MASTER the chaos in you. You are not thrown into the fire, you ARE the fire." - Mama Indigo',
    '"Flowers grow back even after the harshest winters. You will too." - Jennae Cecilia',
    '"Life has many ways of testing a person\'s will, either by having nothing happen at all or by having everything happen all at once." - Paulo Coelho',
    '"Be strong enough to let go and wise enough to wait for what you deserve." - Author Unknown',
    '"It\'s okay to be a glowstick: Sometimes we have to break before we shine." - Jadah Sellner',
    '"Don\'t limit your challenges. Challenge your limits." - Unknown',
    '"Whenever you find yourself doubting how far you can go, just remember how far you have come." - Unknown',
    '"Everyone has inside them a piece of good news. The good news is you don\'t know how great you can be! How much you can love! What you can accomplish! And what your potential is." - Anne Frank',
    '"Some luck lies in not getting what you thought you wanted but getting what you have, which once you have got it you may be smart enough to see is what you would have wanted had you known." - Garrison Keillor',
    '"Don\'t quit yet, the worst moments are usually followed by the most beautiful silver linings. You have to stay strong, remember to keep your head up and remain hopeful." - Unknown',
    '"When written in Chinese the word "crisis" is composed of two characters - one represents danger and the other represents opportunity." - John F Kennedy',
    '"Good. Better. Best. Never let it rest. Til your good is better and your better is best." - St. Jerome.',
    '"In the middle of every difficulty lies opportunity." - Albert Einstein',
    '"Start where you are. Use what you have. Do what you can." - Arthur Ashe',
    '"Dreams don\'t work unless you do." - John C. Maxwell',
    '"Go the extra mile. It\'s never crowded there." - Dr. Wayne D. Dyer',
    '"Keep your face always toward the sunshine - and shadows will fall behind you." - Walt Whitman',
    '"What defines us is how well we rise after falling." - Lionel from Maid in Manhattan Movie',
    'H.O.P.E. = Hold On. Pain Ends.',
    'Make each day your masterpiece. - John Wooden',
    '"Wherever you go, go with all your heart" - Confucius ',
    '"Turn your wounds into wisdom" - Oprah',
    '"We can do anything we want to if we stick to it long enough." - Helen Keller',
    '"Begin anywhere." - John Cage',
]

