quotes=[
    '"I really appreciate people who correct me, because without them, I might have been repeating mistakes for a long time." -Mufti Menk',
    '"Motivation comes from working on things we care about." -Sheryl Sandberg',
    '"If today you are a little bit better than you were yesterday, then that\'s enough." -David A. Bednar',
    '"Education is the most powerful weapon which you can use to change the world." -Nelson Mandela',
    '"If you can\'t make a mistake you can\'t make anything." -Marva Collin',
    '"Practice makes progress not perfect." -Unknown',
    '"You may be disappointed if you fail, but you\'ll be doomed if you don\'t try." -Beverly Sills',
    '"Failure is the tuition you pay for success." -Walter Brunell',
    '"If we wait until we\'re ready, we\'ll be waiting for the rest of our lives." -Lemony Snicket',
    '"Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing." -William Arthur Ward',
    'You\'re so much stronger than your excuses',
    'Don\'t compare yourself to others. Be like the sun and the moon and shine when it\'s your time.',
    'Don\'t Quit',
    'Don\'t tell everyone your plans, instead show them your results.',
    '"No one has ever made a difference by being like everyone else." - The Greatest Showman',
    '"Spend a little more time trying to make something of yourself and a little less time trying to impress people." - The Breakfast Club',
    '"The problem is not the problem. The problem is your attitude about the problem." - Pirates of the Caribbean ',
    '"Remember you\'re the one who can fill the world with sunshine." - Snow White',
    '"You\'ll have bad times, but it\'ll always wake you up to the good stuff you weren\'t paying attention to." - Good Will Hunting',
    '"And when you get the choice to sit it out or dance… I hope you dance." - I Hope You Dance, Lee Ann Womack',
    '"Just because it burns doesn\'t mean you\'re gonna die you\'ve gotta get up and try." - Try, P!nk',
    '"Life\'s a game made for everyone and love is the prize" - Wake Me Up, Avicii',
    '"It\'s a new dawn, it\'s a new day, it\'s a life for me and I\'m feeling good." - Feeling Good, Michael Buble',
    '"Today is where your book begins, the rest is still unwritten." - Unwritten, Natasha Bedingfield',
    '"A million dreams for the world we\'re gonna make\' - The Greatest Showman',
]