quotes=[
    'How to stop time: kiss. How to travel in time: read. How to escape time: music. How to feel time: write. How to release time: breathe." -Matt Haig',
    '"Time is what we want most and what we use worst." - William Penn',
    '"It\'s not about having enough time, it\'s about making enough time." - Rachael Bermingham',
    '"Time is money." - Benjamin Franklin',
    '"Better three hours too soon than a minute too late." - William Shakespeare',
    '"The trouble is, you think you have time." - Buddha',
    '"The greatest gift you could give someone is your time. Because when you give your time, you are giving a portion of your life you can\'t get back." - Unknown',
    '"Punctuality is not just limited to arriving at a place at right time, it is also about taking actions at right time." -Amit Kalantri',
    '"Time always exposes what you mean to someone." - Unknown',
    '"After all this time? Always." - J.K. Rowling',
    '"If you hear a voice within you say you cannot paint,\' then by all means paint and that voice will be silenced." - Vincent Van Gogh',
    '"How wonderful it is that nobody need wait a single moment before starting to improve the world." - Anne Frank',
    '"Some people want it to happen, some wish it would happen, others make it happen." - Michael Jordan',
    '"Great things are done by a series of small things brought together" - Vincent Van Gogh',
    '"If you hire people just because they can do a job, they\'ll work for your money. But if you hire people who believe what you believe, they\'ll work for you with blood and sweat and tears." - Simon Sinek',
    '"Very often, a change of self is needed more than a change of scene.\' - A.C. Benson',
    '"If everything seems to be under control, you\'re not going fast enough." - Mario Andretti',
    '"Opportunity is missed by most people because it is dressed in overalls and looks like work." - Thomas Edison',
    '"The only difference between ordinary and extraordinary is that little extra." - Jimmy Johnson',
    '"The best way to appreciate your job is to imagine yourself without one." - Oscar Wilde',
    '"Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be." - Benjamin Hardy',
    '"Never stop doing your best just because someone doesn\'t give you credit." - Kamari aka Lyrikal',
    '"Work hard for what you want because it won\'t come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive." - Leah LaBelle',
    '"Work hard, be kind, and amazing things will happen." - Conan O\'Brien',
    '"The miracle is not that we do this work, but that we are happy to do it." - Mother Teresa',
    '"Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway." - Earl Nightingale',
    '"If you work on something a little bit every day, you end up with something that is massive." - Kenneth Goldsmith',
    '"The big secret in life is that there is no secret. Whatever your goal, you can get there if you\'re willing to work." - Oprah Winfrey',
    '"If you cannot do great things, do small things in a great way." - Napoleon Hill',
]
