quotes=[
    '"You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win." - Zig Ziglar',
    '"One thing\'s for sure, if you don\'t play, you don\'t win." - Kylie Francis',
    '"Winning means you\'re willing to go longer, work harder, and give more than anyone else." - Vince Lombardi',
    '"Talent wins games, but teamwork wins championships." - Michael Jordan',
    '"When I win and when I lose, I take ownership of it, because I really am in charge of what I do." - Nicki Minaj',
    '"A champion is afraid of losing. Everyone else is afraid of winning." - Billie Jean King',
    '‘Competing at the highest level is not about winning. It\'s about preparation, courage, understanding, nurturing your people, and heart. Winning is the result." - Joe Torre',
    '"A winner is a dreamer who never gives up." - Nelson Mandela',
    '"The secret of your future is hidden in your daily routine." - Mike Murdock',
    '"Losers quit when they fail. Winners fail until they succeed." -Robert T. Kiyosaki',
    '"Leaders can let you fail and yet not let you be a failure." - Stanley McChrystal',
    '"It\'s not the load that breaks you down, it\'s the way you carry it." - Lou Holtz',
    '"The hard days are what make you stronger." - Aly Raisman',
    '"If you believe it\'ll work out, you\'ll see opportunities. If you don\'t believe it\'ll work out, you\'ll see obstacles." - Wayne Dyer',
    '"Keep your eyes on the stars, and your feet on the ground." - Theodore Roosevelt',
    '"You can waste your lives drawing lines. Or you can live your life crossing them." - Shonda Rhimes',
    '"You\'ve got to get up every morning with determination if you\'re going to go to bed with satisfaction." - George Lorimer',
    '"I now tried a new hypothesis: It was possible that I was more in charge of my happiness than I was allowing myself to be." - Michelle Obama',
    '"In a gentle way, you can shake the world." - Mahatma Gandhi',
    'If opportunity doesn\'t knock, build a door." - Kurt Cobain',
    '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart." - Roy T. Bennett',
    '"Work hard in silence, let your success be the noise." - Frank Ocean',
    '"Don\'t say you don\'t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo Da Vinci, Thomas Jefferson, and Albert Einstein." - H. Jackson Brown Jr.',
    '"Hard work beats talent when talent doesn\'t work hard." - Tim Notke',
]

